config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search" => "pages#search", as: "search_page"
    get "/filter" => "pages#filter_via_brand"
    resources :brands, except: [:destroy, :show]
    resources :products, only: [:index, :show]
    resources :comments, only: [:create]
    resources :users, only: [:show, :edit, :update]
    namespace :admin do
      get "/home", to: "static_pages#home"
      resources :brands, except: [:destroy, :show]
      resources :products, except: [:destroy, :show]
    end
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="wrap">
    <div class="section group">
      <div class="col_1_of_4 span_1_of_4">
        <h3><%= t ".info" %></h3>
        <p><%= t ".shop_address" %></p>
      </div>
      <div class="col_1_of_4 span_1_of_4">
        <h3><%= t ".latest_news" %></h3>
        <p><%= t ".news_1" %></p>
        <p><%= t ".news_2" %></p>
      </div>
      <div class="col_1_of_4 span_1_of_4">
        <h3><%= t "base.address" %></h3>
        <p><%= t ".shop_address" %></p>
        <h3><%= t "base.phone" %></h3>
        <p><%= t ".shop_phone" %></p>
      </div>
      <div class="col_1_of_4 span_1_of_4 footer-lastgrid">
        <h3><%= t ".follow_us" %></h3>
          <ul>
            <li><%= link_to image_tag("customer/twitter.png", alt: "twitter"), "#" %></li>
            <li><%= link_to image_tag("customer/facebook.png", alt: "facebook"), "#" %></li>
            <li><%= link_to image_tag("customer/rss.png", alt: "Rss"), "#" %></li>
          </ul>
      </div>
    </div>
  </div>
  <div class="clear"> </div>
  <div class="wrap">
    <div class="copy-right">
      <p>&copy;<%= t ".copy" %></p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="wrap">
  <div class="header">
    <div class="search-bar">
      <%= form_tag(search_page_path, :method => "get",
          class: "navbar-form navbar-left") do %>
        <div class="input-group">
          <%= search_field_tag :search, params[:search], placeholder: t(".s_holder"), class: "form-control" %>
          <div class="input-group-btn">
            <%= button_tag t(".search"), :class => "btn btn-primary glyphicon glyphicon-search",:name => nil %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="clear"> </div>
    <div class="header-top-nav">
      <ul>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "base.account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("base.profile"), current_user %></li>
              <li>
                <%= link_to t("base.logout"), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <li><%= link_to t("base.cart"), "#" %></li>
        <% else %>
          <li><%= link_to t("base.signup"), "#" %></li>
          <li><%= link_to t("base.login"), login_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="clear"> </div>
  </div>
</div>
<div class="clear"></div>
<div class="top-header">
  <div class="wrap">
    <div class="logo">
    <%= link_to image_tag("customer/shop.png", alt: t(".logo")),root_path %>
    </div>
    <div class="top-nav">
      <ul>
        <li><%= link_to t("base.home"), root_path %></li>
        <li><%= link_to t("base.product"), products_path %></li>
        <li><%= link_to t("base.about"), about_path %></li>
        <li><%= link_to t("base.contact"), contact_path %></li>
      </ul>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/_main.erb
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>
<%= render "layouts/footer" %>

app/views/layouts/_right_menu.html.erb
<div class="content-sidebar mt-3">
  <h4 class="text-danger"><%= t "base.brands" %></h4>
    <ul>
      <% get_list_brand.each do |f| %>
        <li><%= link_to f.name, filter_path(id: f.id) %></li>
      <% end %>
    </ul>
</div>

app/views/layouts/_slidebar.html.erb
<div id="demo" class="carousel slide mt-1" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active text-center">
      <%= image_tag("customer/slide2.png", alt: "logo 1") %>
    </div>
    <div class="carousel-item text-center">
      <%= image_tag("customer/slide4.png", alt: "logo 1") %>
    </div>
    <div class="carousel-item text-center">
      <%= image_tag("customer/slide3.png", alt: "logo 1") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

app/views/layouts/_top.html.erb
<div class="top-3-grids">
  <div class="section group">
    <div class="grid_1_of_3 images_1_of_3">
      <li><%= link_to image_tag("customer/tivi6.jpg", alt: "photo"),"#" %></li>
      <h3><%= t ".lg" %></h3>
    </div>
    <div class="grid_1_of_3 images_1_of_3 second">
    <li><%= link_to image_tag("customer/tivi8.jpg", alt: "photo"),"#" %></li>
      <h3><%= t ".samsung" %></h3>
    </div>
      <div class="grid_1_of_3 images_1_of_3 theree">
      <li><%= link_to image_tag("customer/tivi7.jpg", alt: "photo"),"#" %></li>
      <h3><%= t ".panasonic" %></h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".store" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "customer_style", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "sb-admin-2.min", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body id="page-top">
    <div class="m-1">
      <%= link_to t(".english"), locale: :en %>
      <%= link_to t(".vietnamese"), locale: :vi %>
    </div>
    <% if(logged_in? && is_admin?) %>
      <%= render "admin/layouts/main" %>
    <% else %>
      <%= render "layouts/main" %>
    <% end %>
  </body>
</html>